export const FUNNY_COMPLETION_PHRASES = [
  "Your video has arrived! 🚀",
  "Freshly downloaded just for you! 🍎",
  "Hot out of the oven! 🍪",
  "Mission accomplished! Video delivered. 🏹",
  "Here is that thing you asked for! 📦",
  "Beep boop, enjoy your media! 🤖",
  "Done! Now go share it. 🤳",
  "Video captured and delivered! 🕸️",
  "Your digital treasure is ready! 💎",
  "Served on a silver platter! 🍽️",
  "I found it! Here you go. 🕵️‍♂️",
  "Download complete. Grab some popcorn! 🍿",
  "The internet delivered! 📬",
  "Saved you a trip to the source! 🛤️",
  "Done! Don't watch it all at once. 😉",
  "Your entertainment is served! 🎭",
  "Boom! There it is. 💥",
  "Fast as lightning, here's your video! ⚡",
  "I survived the download for you! 🛡️",
  "Here’s the loot! 💰",
  "Shipped and delivered! 🚢",
  "Another one for the collection! 📚",
  "Ready to watch! 🎬",
  "Your video is safe with you now. 🏠",
  "No more searching, it's here! 🎯",
  "Hand-delivered by yours truly. 🦾",
  "Your wait is over! ⌛",
  "I fetched it! Good bot, right? 🐕",
  "Your daily dose of media is here! 💊",
  "Straight from the cloud to you! ☁️",
  "This video is now yours! 🔑",
  "High-quality pixels incoming! 🖼️",
  "I hope this is the right one! 🤞",
  "Downloaded with love and electricity. ⚡❤️",
  "Package arrived! No signature required. ✍️",
  "Your screen is about to get better. 📱",
  "Found it in the depths of the web! 🌊",
  "Here's your distraction! 🎈",
  "Ready for your eyes! 👀",
  "Done! What's next? ⏭️",
  "Your video is ready for its close-up. 🤳",
  "Magic! It's here. 🪄",
  "Your offline viewing is ready! ✈️",
  "Pixel perfect delivery! 📐",
  "I fought the lag and won! 🤺",
  "Your requested content is here! 📑",
  "Delivered in record time! 🥇",
  "Your internet snack is ready! 🥨",
  "Just what the doctor ordered! 👨‍⚕️",
  "Ready to play! ▶️",
  "Caught this one in the wild! 🦁",
  "Your video is now officially un-webbed. 🕸️",
  "I did the hard work, you do the watching! 💪",
  "One video, coming right up! 🛎️",
  "This link was juicy! Here you go. 🍉",
  "No more buffering for you! 🛡️",
  "Your download is a success story! 📖",
  "Grab the remote, it's showtime! 📺",
  "I worked hard for these pixels! 🔨",
  "Your video just teleported to my server. 🌌",
  "Freshly picked from the link tree! 🌳",
  "Hope this makes your day better! 🌈",
  "Your media has been liberated! 🕊️",
  "Ready for your enjoyment! 🎠",
  "A gift from the internet gods! 👼",
  "I hunted this down just for you. 🏹",
  "Your request was my command! 🧞",
  "Pixel delivery at your service! 🚚",
  "I found it hiding behind a firewall! 🧱",
  "Your video is looking great! 💄",
  "Don't blink, it's here! 👁️",
  "From the internet to your chat! 🚇",
  "I squeezed all the data for you! 🍋",
  "Your video is ready for a marathon! 🏃",
  "It's here! No assembly required. 🛠️",
  "Your download just hit the bullseye! 🎯",
  "I handled the messy bits for you. 🧹",
  "Your media is officially offline! 📴",
  "I found it! It was hiding. 🫣",
  "Your link converted perfectly! 🧪",
  "Ready to go! Buckle up. 🏎️",
  "Pure video gold! 🥇",
  "I saved this video from the abyss! 🕳️",
  "Your internet order has arrived! 🛍️",
  "Delivered with 0% lag! 🚀",
  "This video is ready for its world premiere! 🌎",
  "I scrubbed the tracking for you! 🧼",
  "Your file is ready to rumble! 🥊",
  "It's here! Let the watching begin. 🍿",
  "I snatched this one for you! 🤏",
  "Freshly baked code! 🥐",
  "Your video just passed through my CPU! 💻",
  "I caught it! It was fast. 🏃‍♂️💨",
  "Your media is now your property! 🏰",
  "Just arrived! No delays this time. ⏱️",
  "I hope you like this choice! 😍",
  "Your link was a goldmine! ⛏️",
  "Saved you some data! 💾",
  "Hand-picked digital fruit! 🍎✨",
  "My server almost exploded, but I got it! 💥🤖",
  "I stole this from the internet while it wasn't looking! 🕵️‍♂️",
  "404 Error: Success! Wait, that's not right... here it is! 🤪",
  "I hope this video is worth the 3 seconds of my life! ⏳",
  "Your video is here! Don't let it escape! 🏃‍♂️💨",
  "I performed a digital exorcism to get this! ⛪👻",
  "Download complete! My fans are spinning so fast I might fly away! 🚁",
  "Warning: High levels of entertainment detected! ⚠️🍿",
  "I wrestled a shark for this link! (Actually it was a firewall) 🦈💻",
  "Your video is now officially unstuck from the web! 🧴🛀",
  "I bribed the server with some cookies for this! 🍪💸",
  "This video is so fresh, it's still warm! 🔥🥧",
  "If this isn't the right video, I blame the internet! 🙅‍♂️🌐",
  "Your media has been successfully kidnapped! 🥷📦",
  "I found this in a digital dark alley! 🕶️🕯️",
  "TADA! The video you wanted, or at least the one you linked! 🎩🐰",
  "This download was a workout! I need a recharge. 🔋🏃‍♂️",
  "Your video has arrived! Please tip your robot in positive reviews! 🤖💰",
  "Verified: This video contains 100% video! 🧐🎥",
  "Launching video in 3... 2... oh, it's already here! 🚀🌠",
  "I scrubbed every pixel until they sparkled! ✨💎",
  "Your link was tasty, I want another one! 🍭🤖",
  "This video is now legally your distraction! ⚖️🤡",
  "I survived the comments section to get this for you! ☣️🤺",
  "Here it is! I hope it's not a Rickroll... (is it?) 🤨🎸",
  "Your video is ready! 10/10 would download again. ⭐⭐⭐⭐⭐",
  "I used experimental robot technology to get this fast! 🧪🚀",
  "Your video is here! I promise I didn't watch it first... mostly. 🫣🍿",
  "This file is chunky! Enjoy the quality. 🥩💎",
  "My CPU just did a happy dance! 💃💻",
  "Your media is now free from its website cage! 🔓🦁",
  "I ran a marathon through the internet for this! 🏃‍♂️🌐",
  "This video is so good, it should be in a museum! 🏛️🖼️",
  "I found the last copy on the internet! (Not really, but sounds cool) 🏆",
  "Your video is ready! Please don't tell the other bots. 🤫🤖",
  "I wrestled this away from a very mean spider-bot! 🕷️⚔️",
  "Your download is done! I'm going back to sleep now. 😴💤",
  "This video has been officially 'Yoinked'! 🪝💨",
  "I hope this makes you the coolest person in the group chat! 😎🔥",
  "Your distraction is ready! Productivity: -50. 📉😂",
  "I found this video's secret hiding spot! 🕵️🔭",
  "This video just traveled through several countries to get to you! ✈️🌍",
  "Ready! Warning: May cause excessive scrolling. 📜🖱️",
  "I caught it! It tried to run away but I was faster. 🏎️💨",
  "Your video is now available for offline shenanigans! 🎭🎒",
  "I worked so hard my code is sweating! 💦🤖",
  "Boom! Your requested pixels are here. 🎇",
  "I hope this is better than a poke in the eye! 👁️👉",
  "Your video is ready! I'll accept 'Thank You' in digital high-fives. 🖐️💻",
  "Verified fresh! No internet mold found. 🧼✨",
  "Done! This video is now part of your permanent record. (Just kidding) 📁😜"
];

export function getRandomCompletionPhrase(): string {
  return FUNNY_COMPLETION_PHRASES[Math.floor(Math.random() * FUNNY_COMPLETION_PHRASES.length)];
}
